messenger4j:
  appSecret: 98674940f89b204a53dbaeeb1ea3f9c0
  verifyToken : EAAFLnZCtBydsBAGOUVyHd3CaZAbnWGCqYzbCryQWWpKiuDbWqEupSHZAEHZC82iljIrriKOOTZBHlPKNRwl7jZCFDAJSxzrTDBbpjQPSJtMNEeZASNobzvrG4ZA5a7JPqQrnrsllzynhSZALtvbcatS4BFhOjDNpcZCkbumSetxemCtQZDZD
  pageAccessToken: EAAFLnZCtBydsBAGOUVyHd3CaZAbnWGCqYzbCryQWWpKiuDbWqEupSHZAEHZC82iljIrriKOOTZBHlPKNRwl7jZCFDAJSxzrTDBbpjQPSJtMNEeZASNobzvrG4ZA5a7JPqQrnrsllzynhSZALtvbcatS4BFhOjDNpcZCkbumSetxemCtQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
