messenger4j:
  appSecret: e018163100945fc02b691044f3a7103f
  verifyToken : EAAbBZC4HhUGcBAFZCDZA8b1485PkAMpjvK4Y88BH6l9ZB1ZALl2ZALOCndsXmOzHTpNpIAf56oxVjfYkFO0V45wwUI5ZA3DRNhEndKNhR7JZAhZCOGqsidxRkZB751uE6h7SWcvOULmOusZCrEz4GHckZCqF2pOPx2AmJ6bh8Sj6gwkZAiwZDZD
  pageAccessToken: EAAbBZC4HhUGcBAFZCDZA8b1485PkAMpjvK4Y88BH6l9ZB1ZALl2ZALOCndsXmOzHTpNpIAf56oxVjfYkFO0V45wwUI5ZA3DRNhEndKNhR7JZAhZCOGqsidxRkZB751uE6h7SWcvOULmOusZCrEz4GHckZCqF2pOPx2AmJ6bh8Sj6gwkZAiwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
