messenger4j:
  appSecret: 5b52301b7e5b68f4108aa052a53588f6
  verifyToken : EAAB9FdaFn3cBACS3K5tijYOWmoD6TKMeU3xTj11yoxuWCMeNEUH4zqkpIa4B73ZBVcDalOvv6pZCGzlxCkrdpuYzVvGMp6GKFqMuEZC1uKZCNbSLUhZCxgdufJRGBi0nUH57qKvKnVSffZCmCKy2ZAvIBhnfdqZAkGt3ZAyK1oy1LBQZDZD
  pageAccessToken: EAAB9FdaFn3cBAPb1bvXY3N08ZC02gwacf1NFZC8ihXwZAZACZCy1bC91D9uOQRwycpmJn9ZAs5iWEhoxyAJXK4Oig7vYZAFZBtqtc5PSQg4a39mhKPNYQrZC3KO3q6ZCthpL0wlSvj79wVqPFUAaPtnonpM6EZBFNExzU0OZCi9C1ruWjgZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
