messenger4j:
  appSecret: d2ffecb2d30fba0f82a587628c346bb4
  verifyToken : EAAGeF4jlOhMBAGYAFoo1HUEZCzZCT4wrUHMhrkWyZCUn71Jb1ywYZBRzSCnFtcxKdh7yHSKZCVvwxToKxZACz4ICMhDsb3pQITzTfZA744Lll5Dhx9t9erHXjzaZCr2qMpjC4hY8G9s3aSvOgQZCAe1TNm8ZAImF0U2ffdZBd5cBDuELQZDZD
  pageAccessToken: EAAGeF4jlOhMBAGYAFoo1HUEZCzZCT4wrUHMhrkWyZCUn71Jb1ywYZBRzSCnFtcxKdh7yHSKZCVvwxToKxZACz4ICMhDsb3pQITzTfZA744Lll5Dhx9t9erHXjzaZCr2qMpjC4hY8G9s3aSvOgQZCAe1TNm8ZAImF0U2ffdZBd5cBDuELQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
